### ISSUE TITLE
A slice with a midstick on top of it has a background

### ISSUE THREAD

**Issue by SekoiaTree** [Mc-Zen/quill#1]
A slice with a background color, combined with a midstick, will have an extra background color.

Minimal example:
```
#import "@preview/quill:0.2.0" : *
#quantum-circuit({
  let group = gategroup.with(stroke: (dash: "dotted", thickness: 1pt), fill: aqua)
  quantum-circuit(
    row-spacing: 6pt,
    column-spacing: 16pt,
    group(2, 1, label: "Wow"), $H$, [\ ],
    setwire(0), midstick($dots.v$), [\ ],
  ) 
})
```
![image](https://github.com/Mc-Zen/quill/assets/51149447/58e4781c-65da-4913-8a3f-e5ff15450e7f)

Workaround: redefine draw-unboxed-gate and midstick.

```
  let draw-unboxed-gate(gate, draw-params) = box(
    inset: draw-params.padding, 
    fill: if gate.fill != none {gate.fill} else { none }, 
    gate.content
  )
  let midstick(content, label: none) = gate(content, draw-function: draw-unboxed-gate, label: label)
```

**Comment by Mc-Zen** [comment]
Hi @SekoiaTree ,

The reason for it being non-transparent is so that the underlying wires are overdrawn. To illustrate, let's add some wires:
![image](https://github.com/Mc-Zen/quill/assets/52877387/bec238d4-b834-425c-8bb9-f8e0ee2639c0)

Initially, I spent a lot of effort to allow transparent gates and everything but it turned out very tricky with many special cases. It seemed better to not allow transparent gates. For gates, this seems okay to me but I have to admit that I did not think of your case with midstick. 

I see two solutions: 
1) We can add a `fill` parameter to `midstick()`, so you can pass the same background color to it. To use it now, just add the following code to your file:
```typ
#let midstick(content, fill: none, label: none) = gate(content, draw-function: draw-functions.draw-unboxed-gate, label: label, fill: fill)
```
and use it with `midstick(fill: aqua, ...)`

2) The other option is to rewrite a _lot_ of the internals and make transparent gates and co. happen. This is a large effort for not too many benefits but I won't quite say that it will not happen ;)


Thanks for pointing this out!

**Comment by SekoiaTree** [comment]
I don't know hugely much of the internals, but can't you "just" have `slice` pass its own background color as the default setting for the fill?

**Comment by Mc-Zen** [comment]
With 6ebf10, a `fill` parameter has been added to `midstick`. With the new release (v0.2.1), this feature is available (package pull request pending).
