### ISSUE TITLE
How to draw equivalent quantum circuits with "=" in the middle

### ISSUE THREAD

**Issue by zzwe1** [Mc-Zen/quill#10]
Hi, I want to draw two equivalent circuits using Quill like this 
 
![image](https://github.com/user-attachments/assets/bb050b55-b42a-4059-8a36-279f38f2b134)

But I can not split the circuit and add "=" and did not find examples in the user guide, and I create this in a complex way 
```

#grid(
  columns: (auto,auto,auto),
  align: horizon,
  quantum-circuit(
 1, ctrl(1),targ(),ctrl(1),1,[\ ], 
 1, targ(), ctrl(-1),targ(),1 
), 
$=$ ,
quantum-circuit(
  1,swap(1),1, [\ ],
  1,swap(0),1
)
)
```
So is it possible to do this in one quantum-circuit environment?

**Comment by Mc-Zen** [comment]
Hi @zzwe1 ,

I have to apologize: there is an unfinished and unpublished section about this in the manual. I think, the latex package `quantikz` recommends using two circuits for that. This comes with a few tricky parts however since the distance between wires can vary depending on the gates placed on them. This is also discussed in the [quantikz manual](https://mirrors.ibiblio.org/CTAN/graphics/pgf/contrib/quantikz/quantikz.pdf). 

Actually, `quantum-circuit()` features a `baseline` parameter that you can use to just place circuits inline:

```typ
#quantum-circuit(
  baseline: .6fr,
    1, ctrl(1), targ(), ctrl(1), 1, [\ ],
    1, targ(), ctrl(-1), targ(), 1
) = 
#quantum-circuit(
  baseline: .6fr,
    1, swap(1), 1, [\ ],
    1, swap(0), 1
) 
```

You can specify an absolute length or use fractions to place the baseline at a specific wire (`0fr` for the first wire, `1fr` for the second, `0.5fr` exactly in between). Of course, unfortunately, `=` is not centered at the baseline so you need to adjust for that. 


Not ideal, I gotta admit. Probably the best thing would be to add multi-qubit support for `midstick` (as available for `lstick` and `rstick`. In this case, you can just use one circuit.

**Comment by Mc-Zen** [comment]
Seemed pretty easy,

```typ
#quantum-circuit(
  baseline: .6fr,
    1, ctrl(1), targ(), ctrl(1), midstick("=", n: 2), swap(1), 1, [\ ],
    1, targ(), ctrl(-1), targ(), 1, swap(0), 1
) 
```

now produces
![image](https://github.com/user-attachments/assets/e374aa02-9012-4859-bcd8-c7cf2d327dd6)

**Comment by Mc-Zen** [comment]
This will be in the next release. Maybe there should also be options added for braces (like for `lstick` and `rstick`).

**Comment by zzwe1** [comment]
@Mc-Zen Thank you! 

I agree with what you said about this situation and suggest putting it in two circuits. Your first solution is very helpful to me. Looking forward to the next version!
