### ISSUE TITLE
lstick content with equation numbering when turned on

### ISSUE THREAD

**Issue by gdietl** [Mc-Zen/quill#3]
When equation numbering is turned on, the content of lstick and rstick gets an equation number, even if there are no spaces in the expression $...$.

A minimum example is
```
#import "@preview/quill:0.2.1": *

#set math.equation(numbering: "(1)",supplement:[])

#quantum-circuit(
  lstick($rho_"AR"$, n:2), 1, [\ ],
  1, 1,
)
```
producing
![image](https://github.com/Mc-Zen/quill/assets/112486210/2cad3550-8f67-43ea-8772-36de07242ceb)

**Comment by Mc-Zen** [comment]
This is very unfortunate. Actually, the issue is due to the brace `{` which is created in an equation with `block: true`. 

I will definitely fix this for the next release and as soon as possible! However, it's not trivial to get the brace positioning quite right (as I just tried) and I want to do it properly, so that it works for all possible font sizes. 

For now, you could disable equation numbering for each circuit. It might be worth to define 

```typ

#let quantum-circuit1(..args) = {
  set math.equation(numbering: none)
  quantum-circuit(..args)
}

#quantum-circuit1(
  lstick($rho_"AR"$, n:2), 1, [\ ],
  1, 1,
)
```

This should do the trick. 

Thanks for reporting!

**Comment by gdietl** [comment]
Thanks for the quick answer! I have been trying to disable equation numbering for the circuit but unfortunately, it didn't work with my code. However, your code is working! Thanks a lot!
